runtime: nodejs20

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080
  MONGODB_URI: mongodb+srv://roomsync-user:roommate@roomsync.bijkxqe.mongodb.net/?retryWrites=true&w=majority&appName=RoomSync
  GOOGLE_CLIENT_ID: 445076519627-97j67dhhi8pqvkqsts8luanr6pttltbv.apps.googleusercontent.com
  JWT_SECRET: roomsync-super-secret-jwt-key-2024-make-it-very-long-and-secure

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Health check configuration
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network settings
network:
  session_affinity: true

# Resource limits
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
