package com.cpen321.roomsync.ui.navigation

//import android.util.Log
//import androidx.compose.runtime.Composable
//import androidx.compose.runtime.LaunchedEffect
//import androidx.compose.runtime.collectAsState
//import androidx.compose.runtime.getValue
//import androidx.compose.ui.res.stringResource
////import androidx.hilt.navigation.compose.hiltViewModel
////import androidx.navigation.NavHostController
////import androidx.navigation.compose.NavHost
////import androidx.navigation.compose.composable
////import androidx.navigation.compose.rememberNavController
//import com.cpen321.roomsync.R
//import com.cpen321.roomsync.ui.screens.authScreen
//import com.cpen321.roomsync.ui.screens.chatScreen
//import com.cpen321.roomsync.ui.screens.dashboardScreen
//import com.cpen321.roomsync.ui.screens.groupScreen
//import com.cpen321.roomsync.ui.screens.moderationScreen
//import com.cpen321.roomsync.ui.screens.profileScreen
//import com.cpen321.roomsync.ui.screens.ratingScreen
//import com.cpen321.roomsync.ui.screens.taskcreen
//import com.cpen321.roomsync.ui.viewmodels.authViewModel
//import com.cpen321.roomsync.ui.viewmodels.chatViewModel
//import com.cpen321.roomsync.ui.viewmodels.dashboardViewModel
//import com.cpen321.roomsync.ui.viewmodels.groupViewModel